"""fold_hearing.py — hearing is the primitive sense; science is esoterically Pythagorean."""
import json
from pathlib import Path
PATH = Path(__file__).resolve().parents[1] / "KL_DTA.json"
db = json.loads(PATH.read_text(encoding="utf-8"))

db["structure"]["hearing"] = {
    "is": "hearing is the primitive sense; reading = observation = hearing = N. science is esoterically "
          "generated by Pythagorean mathematics.",
    "ear_is_observation": "react = N = the EAR = observation (-sqrt5). reading = X^2 = the primitive "
          "self-action. to READ is to HEAR: observation perceives the spectrum; the act IS hearing.",
    "ear_is_eigendecomposition": "the cochlea/Fourier decomposes a signal into its frequencies = its "
          "EIGENVALUES. hearing perceives the SPECTRUM directly (the raw spectral datum). SPECTRAL "
          "(eigenvalues, light, what observation produces) = HEARD; GEOMETRIC (eigenvectors, gravity, the "
          "carrier) = SEEN. hearing is primitive because the spectrum is the primitive datum (read=X^2); "
          "sight reads geometry THROUGH the matrix, hearing reads the eigenvalues first.",
    "spectrum_is_harmonic": "what the ear hears = the eigenvalues, and these are harmonic: norm(N)^2=2 "
          "(octave), norm(R)^2=3 (fifth), disc=5 (third) — the 5-limit primes; eigenphases = intervals. "
          "'all is number' (Pythagoras): all is the seed P and its ratios; hearing perceives the ratios.",
    "science_is_pythagorean": "the EIGENVALUE PROBLEM (everywhere in physics) IS the vibration/harmonic "
          "problem. quantum mechanics = discrete spectra (energy levels = harmonics); spectroscopy = "
          "literally reading/hearing an atom's spectrum; the harmonic oscillator models everything. beneath "
          "the calculus, science is harmonic ratio — Pythagorean, hidden (esoteric). the framework derives "
          "physics/computation from R^2=R+I, N^2=-I = the octave/fifth structure: it is OVERTLY what science "
          "is covertly — number become sound become world. hearing (N) is the primitive sense that accesses it.",
}
db["structure"]["deepenings"]["hearing_is_primitive_science_is_pythagorean"] = (
    "hearing is the primitive sense: react=N=the ear=observation(-sqrt5); reading=X^2=observe=hear. the ear "
    "is an eigendecomposition (cochlea/Fourier) — it hears the SPECTRUM (eigenvalues=frequencies) directly; "
    "SPECTRAL=heard (light), GEOMETRIC=seen (gravity); hearing primitive because the spectrum is the primitive "
    "datum. the spectrum is harmonic (norm(N)^2=2 octave, norm(R)^2=3 fifth, disc=5 third — Pythagorean). "
    "science is esoterically Pythagorean: the eigenvalue problem IS the vibration problem (quantum spectra, "
    "spectroscopy, the harmonic oscillator); the framework derives it overtly from R^2=R+I/N^2=-I = octave/fifth. "
    "number become sound become world."
)
PATH.write_text(json.dumps(db, indent=2, ensure_ascii=False), encoding="utf-8")
print("hearing + Pythagorean science internalized")
