"""
fold_allconstants.py — L0 is not six constants, it is the generated FIELD.
"""

import json
from pathlib import Path

PATH = Path(__file__).resolve().parents[1] / "KL_DTA.json"
db = json.loads(PATH.read_text(encoding="utf-8"))

origin = db["structure"]["origin"]
origin["all_constants"] = {
    "is": "ALL possible constants = the closure of the seed under +,×,eig,exp,norm — a FIELD, not "
          "a list. the named six (φ,√5,√3,√2,e,π) are landmarks in it.",
    "fibonacci": "R IS the Fibonacci matrix: Rⁿ = [[F_{n−1},F_n],[F_n,F_{n+1}]]. so every Fibonacci "
                 "Fₙ (off-diagonal) and Lucas Lₙ=tr(Rⁿ) is a constant — an INFINITE family, the integer "
                 "lattice ℤ[φ]. det(Rⁿ)=(−1)ⁿ. φⁿ=Fₙ·φ+Fₙ₋₁. the +√5 generation channel counts them out.",
    "family": "the idempotent family disc(k)=1+k² → 2,5,10,17,26: |S₀| · disc(THE seed) · Λ²(5) · "
              "dim_gauge+disc · d_crit. the seed is the k=2 member; the framework's numbers are these discriminants.",
    "closure": "ℤ ⊂ ℤ[φ] (Fibonacci∪Lucas, R-powers) ⊂ ℚ(√5) (golden field) ⊂ ℚ(√2,√3,√5) (adjoin the "
               "norms ‖N‖²=2,‖R‖²=3) ⊕ {i,π,e} (analytic: i,π from N²=−I rotation, e from exp(h)).",
}
origin["invariant_tower"]["L0_spectral"] = (
    "the CONSTANTS — but not a list: the generated field ℚ(√2,√3,√5)⊕{e,π}, integer skeleton the "
    "Fibonacci/Lucas lattice ℤ[φ] (R is the Fibonacci matrix), family disc=1+k². see origin.all_constants."
)

db["structure"]["deepenings"]["all_constants_are_a_field"] = (
    "all possible constants = the field generated by the seed (closure under +,×,eig,exp,norm), not the six "
    "landmarks: R is the Fibonacci matrix so Fₙ,Lₙ ∈ ℤ[φ] are all constants (infinite); family disc=1+k² "
    "→ 2,5,10,17,26; closure ℚ(√2,√3,√5)⊕{e,π}. L0 of the microscope is this whole field."
)

PATH.write_text(json.dumps(db, indent=2, ensure_ascii=False), encoding="utf-8")
print("all-possible-constants (the generated field) internalized into origin")
