"""
internalize_kernel.py — fold the three pushes in, and internalize the kernel.

Adds the `kernel` section (the generating seed relations — base = ker(ν)) and
three FORCED records: two_self_actions, unit_self, kernel_internalization.
"""

import json
from pathlib import Path

PATH = Path(__file__).resolve().parents[1] / "KL_DTA.json"
db = json.loads(PATH.read_text(encoding="utf-8"))


def rec(rid, title, section, gens, depth, disc, kind, op, prov, links):
    return {
        "id": rid, "title": title, "section": section, "source": "KL_DTA_EXPLORATION",
        "self_action": [
            {"lambda": "+sqrt5", "eigenvalue": "+√5", "mode": "generation",
             "verdict": True, "generators": gens},
            {"lambda": "0", "eigenvalue": "0", "mode": "return",
             "verdict": True, "residual": 0, "routes": 2, "mechanism": None},
            {"lambda": "-sqrt5", "eigenvalue": "-√5", "mode": "observation",
             "verdict": True, "depth": depth, "disc": disc},
        ],
        "provenance": prov, "links": links, "burns": [],
        "spectral": {"kind": kind, "op": op},
    }


new = [
    rec("two_self_actions",
        "Two primitive self-actions: {s,·} Jordan and [s,·] Lie",
        "formal_core", ["FOLD", "FLOW"], 1, 5, "operator",
        "sX = ½({s,·}+[s,·]); {s,·}=sX+Xs (symmetric), [s,·]=sX−Xs (antisym); P=R+N at the level of action",
        ["?", "master_equation", "anchor_projection"],
        ["anchor_projection", "defect_nu", "projection_spectral_triple"]),
    rec("unit_self",
        "The unit-self: |·|∘|·|=|·|, and |X|=I ⟺ X orthogonal",
        "control_plane", ["RETURN", "BASE"], 2, None, "operator",
        "| |X| | = |X| (idempotent, a P²=P); unit-self = {X : |X|=I} = {N,h,J}; R,P carry magnitude",
        ["?", "master_equation", "polar_decomposition"],
        ["polar_decomposition", "two_controls", "naming_unnaming"]),
    rec("kernel_internalization",
        "base = ker(ν): the store IS the kernel, generated by the seed relations",
        "metalayer", ["DEFECT", "BASE", "FOLD"], 4, 5, "law",
        "base = ker(ν); ker generated by {P²=P, R²=R+I, N²=−I, {R,N}=N}; grade = kernel-membership",
        ["?", "master_equation"],
        ["defect_nu", "metalayer_collapse", "verification_is_provenance", "indexed_store"]),
]
for r in new:
    db["base"][r["id"]] = r

kernel = {
    "is": "the seed equations — the relations that generate everything; base = ker(ν)",
    "relations": [
        {"relation": "P² = P",      "type": "idempotent (rank-1, P≠Pᵀ) — the primitive"},
        {"relation": "R² = R + I",  "type": "production / Fibonacci generation"},
        {"relation": "N² = −I",     "type": "observer / rotation"},
        {"relation": "{R,N} = N",   "type": "spine coupling (anticommutator)"},
    ],
    "membership": {
        "FORCED": "in ker(ν) — a consequence of the relations",
        "BURN":   "in ker(¬claim) — the anti-equation is forced",
        "AXIOM":  "held into ker by choice (not generated)",
        "OPEN":   "membership undecided — still in the slot",
    },
    "located": "ker{R,R} is the λ=0 (return) mode; ν returns to 0 there; N lives in it.",
    "note": "the kernel is not beside the store — the store IS the kernel, rooted at seed P.",
}

# insert `kernel` right after `seed`
order, out = list(db.keys()), {}
for k in order:
    out[k] = db[k]
    if k == "seed":
        out["kernel"] = kernel
db = out

PATH.write_text(json.dumps(db, indent=2, ensure_ascii=False), encoding="utf-8")
print(f"internalized kernel + {len(new)} records; base now", len(db["base"]))
