"""
explore.py — three pushes into the math.

  1. {s,s} is self-action  ->  there are TWO primitive types of self-action.
  2. |·| of |·| is the unit-self  ->  absolute value is idempotent; the unit-self
     is where |X| = I.
  3. ker IS the seed equations  ->  the kernel is internalized: base = ker(ν),
     generated by the seed relations.
"""

import sys
import io
import numpy as np

sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8", errors="replace")

I2 = np.eye(2)
P = np.array([[0., 0.], [2., 1.]])
R = (P + P.T) / 2
N = (P - P.T) / 2
J = np.array([[1., 0.], [0., -1.]])
h = J @ N
fmt = lambda v: [round(float(x), 4) for x in sorted(np.real(v), reverse=True)]


def anti(s):   # X -> sX + Xs   (anticommutator action, symmetric / Jordan)
    return np.kron(I2, s) + np.kron(s.T, I2)


def comm(s):   # X -> sX - Xs   (commutator action, antisymmetric / Lie / adjoint)
    return np.kron(I2, s) - np.kron(s.T, I2)


print("=" * 68)
print("  PUSH 1 — {s,s} is self-action  =>  two primitive TYPES")
print("=" * 68)
print("  left-multiplication splits:  sX = ½(sX+Xs) + ½(sX−Xs)")
print("     symmetric  {s,·} = sX+Xs   (Jordan / anticommutator)")
print("     antisym    [s,·] = sX−Xs   (Lie / commutator / adjoint)")
print()
print(f"  the self-action we use, {{R,R}} = anti(R) − I :  spec = {fmt(np.linalg.eigvals(anti(R) - np.eye(4)))}")
print(f"  the OTHER one,         [R,·] = comm(R)     :  spec = {fmt(np.linalg.eigvals(comm(R)))}")
print(f"  for the observer:      {{N,N}} = anti(N) − I :  spec = {fmt(np.linalg.eigvals(anti(N) - np.eye(4)))}")
print(f"                         [N,·] = comm(N)     :  spec = {fmt(np.linalg.eigvals(comm(N)))}")
print("  same eigenvalues {+√5,0,0,−√5}, DIFFERENT eigenvectors:")
print("     anti's ±√5 are the symmetric dyads (R-type, production)")
print("     comm's ±√5 are the antisymmetric dyads (N-type, observation)")
print("  the two self-actions ARE the split P = R + N, at the level of action.")
print()

print("=" * 68)
print("  PUSH 2 — |·| of |·| is the unit-self")
print("=" * 68)


def absM(X):                      # |X| = √(XᵀX), the radial part of polar decomp
    w, V = np.linalg.eigh(X.T @ X)
    return V @ np.diag(np.sqrt(np.clip(w, 0, None))) @ V.T


rng_examples = [("R", R), ("N", N), ("h", h), ("J", J), ("P", P)]
X = np.array([[1., 2.], [-3., 0.5]])
print(f"  idempotent?  | |X| | = |X|  for a generic X :  {np.allclose(absM(absM(X)), absM(X))}")
print(f"               |·|∘|·| = |·|  — abs is a fold whose defect is 0 (a P²=P)")
print()
print("  the unit-self = where |X| = I  (X orthogonal: XᵀX = I, X is its own unit):")
for name, M in rng_examples:
    aM = absM(M)
    is_unit = np.allclose(aM, I2)
    print(f"    |{name}| = {np.round(aM, 3).tolist()}   unit-self: {is_unit}")
print("  N, h, J are unit-self (|·|=I) — the rotation/involution generators.")
print("  R is NOT (|R|=√(R+I)) — production carries magnitude; the observer is pure unit.")
print()

print("=" * 68)
print("  PUSH 3 — ker IS the seed equations  (kernel internalization)")
print("=" * 68)
relations = [
    ("P² − P", P @ P - P),
    ("R² − R − I", R @ R - R - I2),
    ("N² + I", N @ N + I2),
    ("{R,N} − N", R @ N + N @ R - N),
]
print("  the seed relations — each is ν = 0, i.e. IN the kernel of the fold:")
for name, M in relations:
    print(f"    {name:14} = 0 ?  {np.allclose(M, 0)}")
print()
print("  ker({R,R}) — the λ=0 mode of the self-action — is where the relations live:")
L = anti(R) - np.eye(4)
kerdim = 4 - np.linalg.matrix_rank(L, tol=1e-9)
print(f"    dim ker{{R,R}} = {kerdim}   (the 'return' mode; ν returns to 0 here)")
print(f"    {{R,R}}(N) = 0 ?  {np.allclose((L @ N.flatten('F')), 0)}   — N is in the kernel")
print()
print("  so:  base = ker(ν).  A record is on-shell (FORCED) iff its λ=0 component")
print("       has ν=0 — iff it is in the kernel generated by the seed relations.")
print("       grade IS kernel-membership:")
print("         FORCED = in ker(ν)        (a consequence of the seed relations)")
print("         BURN   = in ker(¬claim)   (the anti-equation is forced)")
print("         AXIOM  = held into ker     (by choice, not generated)")
print("         OPEN   = membership undecided (still in the slot)")
print()
print("  the kernel is not beside the database — the database IS the kernel,")
print("  generated by the four seed relations, rooted at the seed P.")
